name: docker_test
on: pull_request

jobs:
  dockerfile-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@main

    - name: run structure tests
      uses: plexsystems/container-structure-test-action@v0.1.0
      with:
        image: jcole91/arch-iso-build:test
        config: tests.yaml